---
- credentialType: 'usernamePassword'
  scope: 'GLOBAL'
  username: 'user'
  password: 'pass'
  description: 'This is a sample username/password combination'
  id: 'usernamePassword1'
- credentialType: 'secretText'
  scope: 'GLOBAL'
  secretText: 'This is a secret text'
  description: 'This is a sample secret text credential'
  id: 'secretText1'
- credentialType: 'secretFile'
  scope: 'GLOBAL'
  name: 'sample_secret_file.yml'
  path: 'credentials/sample_secret_file.yml'
  description: 'This is a sample secret file credential'
  id: 'secretFile1'
- credentialType: 'certificate'
  scope: 'GLOBAL'
  path: 'credentials/sampleCertificate.p12'
  password: 'test'
  description: 'This is a sample certificate credential'
  id: 'certificate1'
- credentialType: 'ssh'
  scope: 'GLOBAL'
  username: 'ssh1'
  isJenkinsMasterSsh: False
  path: 'credentials/sampleSsh.pem'
  passphrase: 'password'
  description: 'This is a sample ssh credential from a file'
- credentialType: 'ssh'
  scope: 'GLOBAL'
  username: 'ssh2'
  isJenkinsMasterSsh: True
  passphrase: 'password'
  description: 'This is a sample ssh credential from Jenkins master ~/.ssh'
